[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.virtualenv",
  "gcc",
  "libffi",
  "pkg-config",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "glib",          # Contains libgobject-2.0-0
  "gtk3"           # Also pulls in many related libs
]

[phases.install]
cmds = [
  "python3.11 -m venv /app/venv",
  ". /app/venv/bin/activate && pip install --upgrade pip",
  ". /app/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "/app/venv/bin/gunicorn tile_estimator.wsgi:application"