[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.virtualenv",
  "gcc",
  "libffi",
  "pkg-config",
  "cairo",         # For 2D graphics rendering
  "pango",         # For text layout and rendering
  "gdk-pixbuf",    # For image loading (e.g., PNG, JPEG)
  "glib",          # Core GLib library, often a dependency for GTK-based apps
  "gtk3"           # GTK+ 3, which bundles many of these
]

[phases.install]
cmds = [
  "python3.11 -m venv /app/venv",
  ". /app/venv/bin/activate && pip install --upgrade pip",
  ". /app/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "/app/venv/bin/gunicorn tile_estimator.wsgi:application"