[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "libffi", "pkg-config"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn tile_estimator.wsgi:application"
