[phases.setup]
nixPkgs = ["python311", "python311Packages.virtualenv", "gcc", "libffi", "pkg-config"]

[phases.install]
cmds = [
  "python -m venv /app/venv",
  ". /app/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "/app/venv/bin/gunicorn tile_estimator.wsgi:application"
